config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  namespace :admin do
    resources :articles, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image

  with_options if: :published? do
    validate :image_presence
    validates :title, presence: true
    validates :content, presence: true
  end

  private

  def image_presence
    errors.add(:image, "Image can't be blank") unless image.attached?
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    layout 'admin'
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[edit update destroy]

    def index
      @articles = Article.all
    end

    def new
      @article = Article.new
    end

    def edit; end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to %i[admin articles], notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to %i[admin articles], notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to %i[admin articles], notice: 'Article was successfully destroyed.'
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:content, :image, :published, :title)
      # params.fetch(:article, {})
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.erb
<%= form_with(model: [:admin, article], local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :published %>
  <%= form.check_box :published %>

  <%= form.label :title %>
  <%= form.text_field :title, size: 80 %>

  <%= form.label :image %>
  <%= form.file_field :image %>

  <%= form.label :content %>
  <%= form.text_area :content, cols: 80, rows: 20 %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', [:admin, :articles] %>

app/views/admin/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class='articles'>
  <thead>
    <tr>
      <th>Created At</th>
      <th>Published</th>
      <th>Title</th>
      <th>Content</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td class='created_at'><%= l(article.created_at, format: :short) %></td>
        <td class='published'><%= t(article.published?) %></td>
        <td class='title'><%= article.title %></td>
        <td class='content'><%= truncate(article.content, length: 50) %></td>
        <td>
          <%= link_to 'Edit', [:edit, :admin, article] %>
          <%= link_to 'Destroy', [:admin, article], method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', %i[new admin article] %>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', [:admin, :articles] %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', [:admin, :articles] %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5Playground</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5Playground</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'hello_react' %>
  </body>
</html>